### ISSUE TITLE
include the babel-plugin-istanbul so nyc coverage is reported correctly

### ISSUE THREAD

**Issue by travi** [form8ion/javascript-core#84]
[this commit](https://github.com/pragmatic-divops/cli/commit/b7623ef6b99d5a7bb51602dbcef7004cddaea08f) fixed the problem of reporting zero coverage, but we should probably only include the plugin for `NODE_ENV=test`, or whatever is set for mocha tests. maybe the plugin already excludes itself for `NODE_ENV=production`?

**Comment by travi** [comment]
if we find that we need to do conditional inclusion in a `.babelrc`, lets make sure [this one](https://github.com/pragmatic-divops/cli/blob/master/.babelrc) gets updated

**Comment by trevtrich** [comment]
@travi did you mean to point to the cli in your pragmatic div-ops repo or the one in form8ion? it does look like we need to do conditional inclusion. I added cross-env into the `javascript-core` repo [here](https://github.com/form8ion/javascript-core/commit/47bd925c18a2858d91bef5ba595498802e4e00d4) so that we'd have the right hook to key on in node_env, but we'll also need to add the conditional inclusion logic to the root babelrc, which I'm assuming is [this one in `travi/javascript-scaffolder`](https://github.com/travi/javascript-scaffolder/blob/master/src/config/babel.js)?

**Comment by travi** [comment]
> did you mean to point to the cli in your pragmatic div-ops repo or the one in form8ion?

i pointed to the pragmatic-divops one because it was the first project that i scaffolded where this was a problem that i needed to fix manually. i just want to apply whatever fix we come up with for new projects to that one as well.

> I added cross-env into the javascript-core repo here so that we'd have the right hook to key on in node_env

are you just using `cross-env` for windows support or something else? i'm ok with not worrying about cross platform support at this point if it complicates anything

> which I'm assuming is this one in travi/javascript-scaffolder?

yeah, thats the current way we handle it. havent given much thought to how would be best to include something like that, so i'm open to options

**Comment by trevtrich** [comment]
> are you just using cross-env for windows support or something else? i'm ok with not worrying about cross platform support at this point if it complicates anything

purely out of feeling like it'd be good practice. 

> yeah, thats the current way we handle it. havent given much thought to how would be best to include something like that, so i'm open to options

will keep in mind, but right off hand can't think of anything that feels like a solid direction.

**Comment by travi** [comment]
> purely out of feeling like it'd be good practice.

ok, cool. thats totally reasonable. i wonder if there are other scripts like this that would be inconsistent. inconsistency with this isnt the end of the world, but would be good to apply the same approach if we spot any

> will keep in mind, but right off hand can't think of anything that feels like a solid direction.

my thoughts come back to the goal of write a simple-ish initial version and modify afterward with conditional content. i dont want to block solving the coverage stuff with the complexity of solving how to do that with js files, but its worth keeping on the table as an option if we don't come up with something simpler
